name: Deploy to Azure Container App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/house-price-api:${{ github.sha }} .

      - run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/house-price-api:${{ github.sha }}

      - run: |
          az containerapp update \
            --name house-price-api-app \
            --resource-group mlops-rg \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/house-price-api:${{ github.sha }}
