name: Deploy to Azure Container App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build & Push Image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/house-price-api:${{ github.sha }}
          docker build --no-cache -t $IMAGE .
          docker push $IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/house-price-api:${{ github.sha }}
          echo "Deploying $IMAGE"
          az containerapp update \
            --name house-price-api-app \
            --resource-group mlops-rg \
            --image $IMAGE